/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Jun 22 10:25:55 GMT 2025
 */

package org.apache.openjpa.util;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ProxyManagerImpl_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  protected static ExecutorService executor; 

  private static final java.util.Properties defaultProperties = (java.util.Properties) System.getProperties().clone();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.openjpa.util.ProxyManagerImpl"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = SandboxMode.RECOMMENDED;
    Sandbox.initializeSecurityManagerForSUT();
    executor = Executors.newCachedThreadPool(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    executor.shutdownNow(); 
    System.setProperties((java.util.Properties) defaultProperties.clone());
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    Sandbox.goingToExecuteSUTCode();
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    Sandbox.doneWithExecutingSUTCode();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    System.setProperties((java.util.Properties) defaultProperties.clone());
    System.setProperty("file.encoding", "UTF-8");
    System.setProperty("user.dir", "/home/flavio/Progetti/openjpa/openjpa-kernel");
    System.setProperty("java.io.tmpdir", "/tmp");
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ProxyManagerImpl_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.openjpa.lib.util.StreamResourceBundleProvider",
      "org.apache.openjpa.lib.util.EventManager",
      "org.apache.openjpa.enhance.PersistenceCapable",
      "org.apache.openjpa.event.CallbackModes",
      "org.apache.openjpa.lib.util.ZipResourceBundleProvider",
      "org.apache.openjpa.event.RemoteCommitListener",
      "org.apache.openjpa.kernel.DetachedStateManager",
      "org.apache.openjpa.meta.MetaDataModes",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashMap$Entry",
      "org.apache.openjpa.kernel.TransferFieldManager",
      "org.apache.xbean.asm9.ClassVisitor",
      "org.apache.openjpa.meta.ClassMetaData",
      "org.apache.openjpa.datacache.DataCacheManager",
      "org.apache.openjpa.util.GeneralException",
      "org.apache.openjpa.util.proxy.DelayedProxy",
      "org.apache.openjpa.util.AbstractChangeTracker",
      "org.apache.openjpa.lib.util.SizedMap",
      "org.apache.xbean.asm9.MethodVisitor",
      "org.apache.openjpa.lib.conf.ValueListener",
      "org.apache.openjpa.meta.MetaDataContext",
      "org.apache.openjpa.util.proxy.ProxyMaps",
      "org.apache.openjpa.lib.log.Log",
      "org.apache.openjpa.util.MapChangeTracker",
      "org.apache.openjpa.util.ChangeTracker",
      "org.apache.openjpa.util.UserException",
      "org.apache.xbean.asm9.tree.MethodInsnNode",
      "org.apache.openjpa.lib.util.StringUtil",
      "org.apache.openjpa.util.proxy.ProxyCollections$ProxyIterator",
      "org.apache.openjpa.kernel.LockScopes",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceStrength",
      "org.apache.openjpa.kernel.PCData",
      "org.apache.openjpa.util.CollectionChangeTrackerImpl",
      "org.apache.xbean.asm9.FieldWriter",
      "org.apache.openjpa.lib.util.SimpleResourceBundleProvider",
      "org.apache.openjpa.kernel.Broker",
      "org.apache.openjpa.datacache.CacheStatistics",
      "org.apache.openjpa.lib.meta.SourceTracker",
      "org.apache.openjpa.kernel.AutoDetach",
      "org.apache.openjpa.util.CollectionChangeTracker",
      "org.apache.openjpa.enhance.PCRegistry",
      "org.apache.openjpa.datacache.CacheStatisticsImpl",
      "org.apache.openjpa.kernel.QueryFlushModes",
      "org.apache.openjpa.util.ClassLoaderProxyService",
      "org.apache.openjpa.kernel.AttachManager",
      "org.apache.xbean.asm9.ByteVector",
      "org.apache.openjpa.util.proxy.ProxyCollections",
      "org.apache.xbean.asm9.MethodTooLargeException",
      "org.apache.xbean.asm9.tree.TypeInsnNode",
      "org.apache.openjpa.lib.util.J2DoPrivHelper",
      "org.apache.openjpa.lib.util.ReferenceMap",
      "org.apache.openjpa.kernel.LockLevels",
      "org.apache.openjpa.util.OpenJPAException",
      "org.apache.openjpa.util.ProxyManager",
      "org.apache.openjpa.datacache.ConcurrentDataCache$1",
      "org.apache.xbean.asm9.tree.InsnNode",
      "org.apache.openjpa.util.ImplHelper$1",
      "org.apache.openjpa.datacache.DataCachePCData",
      "org.apache.openjpa.kernel.StoreContext",
      "org.apache.openjpa.util.UnsupportedException",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$38",
      "org.apache.openjpa.lib.util.Clearable",
      "org.apache.openjpa.event.RemoteCommitEvent",
      "org.apache.xbean.asm9.Type",
      "org.apache.openjpa.datacache.DataCache",
      "org.apache.xbean.asm9.Attribute",
      "org.apache.openjpa.datacache.AbstractDataCache",
      "org.apache.openjpa.kernel.AttachStrategy",
      "org.apache.openjpa.meta.ValueMetaData",
      "org.apache.openjpa.util.proxy.DelayedLinkedHashSetProxy",
      "org.apache.openjpa.datacache.CacheStatisticsSPI",
      "org.apache.openjpa.util.InvalidStateException",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$5",
      "org.apache.openjpa.kernel.ObjectIdStateManager",
      "org.apache.xbean.asm9.SymbolTable$Entry",
      "org.apache.openjpa.util.Proxies",
      "org.apache.xbean.asm9.Frame",
      "org.apache.xbean.asm9.AnnotationWriter",
      "org.apache.openjpa.lib.util.concurrent.AbstractConcurrentEventManager",
      "org.apache.xbean.asm9.Label",
      "org.apache.openjpa.kernel.BrokerFactory",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentMap",
      "org.apache.xbean.asm9.ModuleVisitor",
      "org.apache.openjpa.kernel.OpenJPAStateManager",
      "org.apache.openjpa.util.proxy.ProxyBean",
      "org.apache.openjpa.util.proxy.ProxyDate",
      "org.apache.openjpa.util.proxy.ProxyCollections$ProxyListIterator",
      "org.apache.openjpa.util.DelayedCollectionChangeTrackerImpl",
      "org.apache.openjpa.util.proxy.DelayedLinkedListProxy",
      "org.apache.openjpa.lib.util.Files",
      "org.apache.openjpa.kernel.RestoreState",
      "org.apache.openjpa.lib.conf.Configurable",
      "org.apache.xbean.asm9.Handler",
      "org.apache.openjpa.lib.util.Closeable",
      "org.apache.xbean.asm9.RecordComponentWriter",
      "org.apache.xbean.asm9.tree.AbstractInsnNode",
      "org.apache.openjpa.util.proxy.ProxyCalendar",
      "org.apache.openjpa.util.asm.RedefinedAttribute",
      "org.apache.openjpa.util.proxy.ProxyMaps$ProxyEntrySetImpl$1",
      "org.apache.openjpa.lib.conf.Configuration",
      "org.apache.openjpa.util.proxy.DelayedPriorityQueueProxy",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$10",
      "org.apache.openjpa.enhance.StateManager",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$11",
      "org.apache.openjpa.lib.util.ResourceBundleProvider",
      "org.apache.xbean.asm9.AnnotationVisitor",
      "org.apache.openjpa.lib.util.TypedProperties",
      "org.apache.openjpa.lib.util.ClassUtil",
      "org.apache.openjpa.util.CacheMap",
      "org.apache.xbean.asm9.CurrentFrame",
      "org.apache.openjpa.util.InternalException",
      "org.apache.openjpa.kernel.AutoClear",
      "org.apache.openjpa.util.Proxy",
      "org.apache.xbean.asm9.tree.FieldInsnNode",
      "org.apache.openjpa.enhance.FieldConsumer",
      "org.apache.xbean.asm9.MethodWriter",
      "org.apache.openjpa.kernel.DetachState",
      "org.apache.openjpa.util.asm.BCClassWriter",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashSet",
      "org.apache.openjpa.util.GeneratedClasses",
      "org.apache.openjpa.lib.util.ParseException",
      "org.apache.xbean.asm9.tree.IntInsnNode",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashMap",
      "org.apache.openjpa.lib.util.collections.MapBackedSet",
      "org.apache.openjpa.util.proxy.ProxyCollection",
      "org.apache.xbean.asm9.Edge",
      "org.apache.openjpa.kernel.FetchConfiguration",
      "org.apache.openjpa.util.proxy.DelayedTreeSetProxy",
      "org.apache.openjpa.util.ProxyManagerImpl",
      "org.apache.openjpa.util.proxy.ProxyMaps$ProxyEntrySet",
      "org.apache.xbean.asm9.FieldVisitor",
      "org.apache.openjpa.util.proxy.ProxyMaps$ProxyEntrySetImpl",
      "org.apache.openjpa.lib.xml.Commentable",
      "org.apache.openjpa.lib.util.Localizer",
      "org.apache.xbean.asm9.RecordComponentVisitor",
      "org.apache.openjpa.util.MapChangeTrackerImpl",
      "org.apache.xbean.asm9.ClassTooLargeException",
      "jakarta.transaction.Synchronization",
      "org.apache.openjpa.enhance.FieldSupplier",
      "org.apache.openjpa.datacache.ConcurrentDataCache",
      "org.apache.openjpa.datacache.ExpirationListener",
      "org.apache.openjpa.kernel.DetachedValueStateManager",
      "org.apache.openjpa.enhance.FieldManager",
      "org.apache.xbean.asm9.Symbol",
      "org.apache.openjpa.util.asm.ClassWriterTracker",
      "org.apache.openjpa.kernel.PCState",
      "org.apache.openjpa.util.asm.AsmHelper",
      "org.apache.openjpa.util.proxy.DelayedHashSetProxy",
      "org.apache.openjpa.util.proxy.DelayedArrayListProxy",
      "org.apache.xbean.asm9.ClassWriter",
      "org.apache.xbean.asm9.tree.LdcInsnNode",
      "org.apache.openjpa.util.ImplHelper",
      "org.apache.openjpa.util.ClassLoaderProxyService$ProxiesClassLoader",
      "org.apache.openjpa.util.proxy.DelayedVectorProxy",
      "org.apache.xbean.asm9.ModuleWriter",
      "org.apache.xbean.asm9.SymbolTable",
      "org.apache.openjpa.meta.Extensions",
      "org.apache.openjpa.lib.util.Options",
      "org.apache.openjpa.lib.util.Localizer$Message",
      "org.apache.openjpa.util.proxy.ProxyMap",
      "org.apache.xbean.asm9.tree.ClassNode",
      "org.apache.openjpa.util.proxy.ProxyCollections$1",
      "org.apache.openjpa.util.proxy.ProxyCollections$2",
      "org.apache.openjpa.util.ExceptionInfo",
      "org.apache.openjpa.lib.util.OrderedMap",
      "org.apache.openjpa.kernel.ConnectionRetainModes",
      "org.apache.openjpa.lib.util.Options$EmptyOptions"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.util.Comparator", false, ProxyManagerImpl_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ProxyManagerImpl_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.openjpa.lib.util.SimpleResourceBundleProvider",
      "org.apache.openjpa.lib.util.StreamResourceBundleProvider",
      "org.apache.openjpa.lib.util.ZipResourceBundleProvider",
      "org.apache.openjpa.lib.util.Localizer",
      "org.apache.openjpa.lib.util.J2DoPrivHelper",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$5",
      "org.apache.xbean.asm9.Type",
      "org.apache.openjpa.util.ProxyManagerImpl",
      "org.apache.openjpa.lib.util.StringUtil",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceStrength",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashMap",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashSet",
      "org.apache.openjpa.lib.util.collections.MapBackedSet",
      "org.apache.openjpa.enhance.PCRegistry",
      "org.apache.openjpa.lib.util.ClassUtil",
      "org.apache.openjpa.util.GeneratedClasses",
      "org.apache.openjpa.util.OpenJPAException",
      "org.apache.openjpa.util.UnsupportedException",
      "org.apache.openjpa.lib.util.Localizer$Message",
      "org.apache.openjpa.util.proxy.DelayedHashSetProxy",
      "org.apache.openjpa.lib.util.Files",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$10",
      "org.apache.openjpa.lib.util.TypedProperties",
      "org.apache.openjpa.lib.util.Options$EmptyOptions",
      "org.apache.openjpa.lib.util.Options",
      "org.apache.openjpa.util.Proxies",
      "org.apache.openjpa.util.proxy.ProxyCollections",
      "org.apache.openjpa.util.ImplHelper$1",
      "org.apache.openjpa.util.ImplHelper",
      "org.apache.xbean.asm9.ClassVisitor",
      "org.apache.xbean.asm9.ClassWriter",
      "org.apache.xbean.asm9.SymbolTable",
      "org.apache.xbean.asm9.ByteVector",
      "org.apache.xbean.asm9.Symbol",
      "org.apache.xbean.asm9.SymbolTable$Entry",
      "org.apache.openjpa.util.asm.ClassWriterTracker",
      "org.apache.xbean.asm9.Attribute",
      "org.apache.openjpa.util.asm.RedefinedAttribute",
      "org.apache.openjpa.util.asm.AsmHelper",
      "org.apache.xbean.asm9.MethodVisitor",
      "org.apache.xbean.asm9.MethodWriter",
      "org.apache.xbean.asm9.Label",
      "org.apache.xbean.asm9.Frame",
      "org.apache.xbean.asm9.FieldVisitor",
      "org.apache.xbean.asm9.FieldWriter",
      "org.apache.xbean.asm9.AnnotationVisitor",
      "org.apache.xbean.asm9.AnnotationWriter",
      "org.apache.xbean.asm9.Handler",
      "org.apache.openjpa.util.ClassLoaderProxyService",
      "org.apache.openjpa.util.ClassLoaderProxyService$ProxiesClassLoader",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$11",
      "org.apache.openjpa.util.proxy.DelayedVectorProxy",
      "org.apache.openjpa.util.proxy.ProxyCollections$1",
      "org.apache.openjpa.util.GeneralException",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$1",
      "org.apache.openjpa.lib.conf.ConfigurationImpl",
      "org.apache.openjpa.conf.OpenJPAConfigurationImpl",
      "org.apache.openjpa.lib.conf.Value",
      "org.apache.openjpa.lib.conf.ObjectValue",
      "org.apache.openjpa.lib.conf.PluginValue",
      "org.apache.openjpa.lib.conf.Configurations",
      "org.apache.openjpa.lib.conf.StringValue",
      "org.apache.openjpa.util.StoreFacadeTypeRegistry",
      "org.apache.openjpa.lib.util.concurrent.AbstractConcurrentEventManager",
      "org.apache.openjpa.event.BrokerFactoryEventManager",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$49",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$16",
      "org.apache.openjpa.lib.util.MultiClassLoader",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$40",
      "org.apache.openjpa.lib.util.Services",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$15",
      "org.apache.openjpa.lib.conf.ProductDerivations",
      "org.apache.openjpa.conf.BrokerFactoryValue",
      "org.apache.xbean.asm9.Edge",
      "org.apache.openjpa.util.proxy.DelayedLinkedListProxy",
      "org.apache.openjpa.util.proxy.DelayedArrayListProxy",
      "org.apache.openjpa.util.proxy.DelayedPriorityQueueProxy",
      "org.apache.openjpa.util.AbstractChangeTracker",
      "org.apache.openjpa.util.MapChangeTrackerImpl",
      "org.apache.openjpa.datacache.AbstractQueryCache",
      "org.apache.openjpa.datacache.ConcurrentQueryCache",
      "org.apache.openjpa.datacache.AbstractQueryCache$EvictPolicy",
      "org.apache.openjpa.util.proxy.ProxyMaps",
      "org.apache.openjpa.util.proxy.ProxyMaps$ProxyEntrySetImpl",
      "org.apache.openjpa.util.proxy.ProxyMaps$ProxyEntrySetImpl$1",
      "org.apache.openjpa.kernel.ObjectIdStateManager",
      "org.apache.openjpa.kernel.exps.Val",
      "org.apache.openjpa.kernel.exps.CandidatePath",
      "org.apache.openjpa.meta.MetaDataRepository",
      "org.apache.openjpa.event.LifecycleEventManager$ListenerList",
      "org.apache.openjpa.util.proxy.ProxyCollections$2",
      "org.apache.openjpa.kernel.TransferFieldManager",
      "org.apache.openjpa.kernel.AttachStrategy",
      "org.apache.openjpa.kernel.DetachedStateManager",
      "org.apache.openjpa.util.proxy.DelayedLinkedHashSetProxy",
      "org.apache.openjpa.kernel.StateManagerImpl",
      "org.apache.openjpa.lib.util.OrderedMap",
      "org.apache.openjpa.util.proxy.DelayedTreeSetProxy",
      "org.apache.openjpa.kernel.DetachedValueStateManager",
      "org.apache.openjpa.kernel.DelegatingExtent",
      "org.apache.openjpa.util.CollectionChangeTrackerImpl",
      "org.apache.openjpa.util.DelayedCollectionChangeTrackerImpl",
      "org.apache.openjpa.kernel.BrokerImpl",
      "org.apache.openjpa.kernel.FinalizingBrokerImpl",
      "org.apache.openjpa.kernel.jpql.JPQLParser",
      "org.apache.openjpa.kernel.AbstractStoreQuery",
      "org.apache.openjpa.kernel.exps.StringContains",
      "org.apache.openjpa.kernel.exps.WildcardMatch",
      "org.apache.openjpa.kernel.ExpressionStoreQuery",
      "org.apache.openjpa.kernel.QueryImpl",
      "org.apache.openjpa.lib.util.ReferenceHashSet$1",
      "org.apache.openjpa.lib.util.ReferenceHashSet",
      "org.apache.openjpa.lib.util.collections.AbstractHashedMap",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap",
      "org.apache.openjpa.lib.util.collections.ReferenceMap",
      "org.apache.openjpa.kernel.jpql.JPQLExpressionBuilder$ParsedJPQL",
      "org.apache.openjpa.kernel.exps.Null",
      "org.apache.openjpa.kernel.exps.InMemoryExpressionFactory",
      "org.apache.openjpa.kernel.exps.SubQ",
      "org.apache.openjpa.kernel.exps.QueryExpressions",
      "org.apache.openjpa.lib.util.collections.AbstractLinkedMap",
      "org.apache.openjpa.lib.util.collections.LinkedMap",
      "org.apache.openjpa.lib.util.collections.AbstractHashedMap$HashEntry",
      "org.apache.openjpa.lib.util.collections.AbstractLinkedMap$LinkEntry",
      "org.apache.openjpa.kernel.StoreQuery",
      "org.apache.openjpa.lib.instrumentation.AbstractInstrument",
      "org.apache.openjpa.instrumentation.AbstractQueryCacheInstrument",
      "org.apache.openjpa.instrumentation.jmx.QueryCacheJMXInstrument",
      "org.apache.openjpa.instrumentation.AbstractPreparedQueryCacheInstrument",
      "org.apache.openjpa.instrumentation.jmx.PreparedQueryCacheJMXInstrument",
      "org.apache.openjpa.meta.Extensions",
      "org.apache.openjpa.kernel.DelegatingBroker",
      "org.apache.openjpa.util.UserException",
      "org.apache.openjpa.util.Exceptions$1",
      "org.apache.openjpa.util.Exceptions",
      "org.apache.openjpa.meta.AccessCode",
      "org.apache.openjpa.meta.ClassMetaData",
      "org.apache.openjpa.meta.LifecycleMetaData",
      "org.apache.openjpa.datacache.AbstractDataCache",
      "org.apache.openjpa.datacache.ConcurrentDataCache",
      "org.apache.openjpa.datacache.PartitionedDataCache",
      "org.apache.openjpa.datacache.CacheStatisticsImpl",
      "org.apache.openjpa.kernel.PNewState",
      "org.apache.openjpa.kernel.PCleanState",
      "org.apache.openjpa.kernel.PDirtyState",
      "org.apache.openjpa.kernel.PDeletedState",
      "org.apache.openjpa.kernel.PNewDeletedState",
      "org.apache.openjpa.kernel.PNewProvisionalState",
      "org.apache.openjpa.kernel.PNonTransState",
      "org.apache.openjpa.kernel.PNonTransDirtyState",
      "org.apache.openjpa.kernel.PNonTransNewState",
      "org.apache.openjpa.kernel.PNonTransDeletedState",
      "org.apache.openjpa.kernel.HollowState",
      "org.apache.openjpa.kernel.TransientState",
      "org.apache.openjpa.kernel.TCleanState",
      "org.apache.openjpa.kernel.TDirtyState",
      "org.apache.openjpa.kernel.TLoadedState",
      "org.apache.openjpa.kernel.ECopyState",
      "org.apache.openjpa.kernel.ECleanState",
      "org.apache.openjpa.kernel.EDirtyState",
      "org.apache.openjpa.kernel.EDeletedState",
      "org.apache.openjpa.kernel.ENonTransState",
      "org.apache.openjpa.kernel.PNewFlushedDeletedState",
      "org.apache.openjpa.kernel.PNewFlushedDeletedFlushedState",
      "org.apache.openjpa.kernel.PDeletedFlushedState",
      "org.apache.openjpa.kernel.PCState",
      "org.apache.openjpa.kernel.SingleFieldManager",
      "org.apache.openjpa.util.ClassResolverImpl",
      "org.apache.openjpa.util.InvalidStateException",
      "org.apache.openjpa.instrumentation.AbstractDataCacheInstrument",
      "org.apache.openjpa.instrumentation.jmx.DataCacheJMXInstrument",
      "org.apache.openjpa.util.NoTransactionException",
      "org.apache.openjpa.util.MultiLoaderClassResolver",
      "org.apache.openjpa.util.MetaDataException",
      "jakarta.jms.JMSException",
      "org.apache.openjpa.ee.AbstractManagedRuntime",
      "org.apache.openjpa.ee.AutomaticManagedRuntime",
      "org.apache.openjpa.ee.RegistryManagedRuntime",
      "org.apache.openjpa.ee.WLSManagedRuntime",
      "org.apache.openjpa.ee.SunOneManagedRuntime",
      "org.apache.openjpa.ee.WASManagedRuntime",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$4",
      "org.apache.openjpa.ee.WASRegistryManagedRuntime",
      "org.apache.openjpa.ee.RegistryManagedRuntime$TransactionManagerRegistryFacade",
      "org.apache.openjpa.ee.JNDIManagedRuntime",
      "org.apache.openjpa.ee.InvocationManagedRuntime",
      "org.apache.openjpa.kernel.ResultShape",
      "org.apache.openjpa.kernel.FillStrategy$Assign",
      "org.apache.openjpa.datacache.QueryKey",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$38"
    );
  }
}
